### ISSUE TITLE
[BUG] The number of columns does not match.

### ISSUE THREAD

**Issue by neominky** [JanoPL/Routeslist#70]
The number of columns does not match.
Is it correct to remove "!string.IsNullOrEmpty(ListRoutes[0].Template)" from the conditional clause? (177th line of TableBuilder.cs)

![image](https://github.com/JanoPL/Routeslist/assets/32407205/ee56c1dd-ef44-497c-83bc-2e5d8071b83a)
<img width="1299" alt="image" src="https://github.com/JanoPL/Routeslist/assets/32407205/71c19a7a-deb1-47f3-8b33-ee56bf262247">
![image](https://github.com/JanoPL/Routeslist/assets/32407205/b86534af-5293-4c11-b7b2-87f77c294437)
![image](https://github.com/JanoPL/Routeslist/assets/32407205/7ed477d6-ff94-4e7c-92d4-7cefcff75bc9)

**Comment by JanoPL** [comment]
Hi, 
I will check this error, maybe they changed something.

Can you describe what version of .net you are using and what component your project uses razor/blazor/MVC?

It would also be helpful to have information on how I can reproduce your error on my side.

It can be a sample empty project with a few endpoints.

Alternatively, if your project uses a hybrid of multiple components, how do you do that and what do your endpoints look like?

**Comment by JanoPL** [comment]
for sure it should be String not string sorry for my mistake :)

**Comment by neominky** [comment]
of course. Here's how to reproduce it.

Framework : .NET 7
Project Template : ASP.NET Core Web API
Creation Options : Default options

add three lines in Main()

builder.Services.AddRoutesList();
app.UseRouting();
app.UseRoutesList();

`using RoutesList.Gen;

namespace testweb2
{
	public class Program
	{
		public static void Main(string[] args)
		{
			var builder = WebApplication.CreateBuilder(args);

			// Add services to the container.

			builder.Services.AddControllers();
			// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
			builder.Services.AddEndpointsApiExplorer();
			builder.Services.AddSwaggerGen();
			builder.Services.AddRoutesList();
			var app = builder.Build();

			// Configure the HTTP request pipeline.
			if (app.Environment.IsDevelopment())
			{
				app.UseSwagger();
				app.UseSwaggerUI();
			}

			app.UseHttpsRedirection();
			
			app.UseRouting();
			app.UseAuthorization();

			app.MapControllers();
			
			app.UseRoutesList();
			app.Run();
		}
	}
}`
It's very simple.  This reproduces the error.
To save energy and reduce CO2, files will not be attached. =D

but my real project has a default endpoint here
			app.MapControllerRoute(
				name: "default",
				pattern: "{controller=Home}/{action=Index}/{id?}");

and default home controller
	[Route("Home")]
	public class HomeController : Controller
	{
		public IActionResult Index()
		{
			return Json("Hello");
		}
	}

**Comment by JanoPL** [comment]
I released changes to the repo regarding the detection of what type of endpoint you have in the application

I tested it on a sample controller, if you had something unusual and something didn’t work let me know

I will try to release the package today or tomorrow there should be a newer version with fixes on nuget.org

Home Controller 
```C#
namespace WebApplication1.Controllers
{
    [Route("Home1")]
    public class HomeController : Controller
    {
        [HttpGet(template: "1")]
        public IActionResult Index()
        {
            return Json("hello world");
        }

        [HttpGet(template: "2")]
        public IActionResult Index2()
        {
            return Json("hello world");
        }
    }

    [Route("Home2")]
    public class Home2Controller : Controller
    {
        public IActionResult Index()
        {
            return Json("fancy controller");
        }
    }
}
```

![image](https://github.com/JanoPL/Routeslist/assets/37768741/ff46c938-9e95-4c5a-bf1c-4e0145ba9264)

**Comment by neominky** [comment]
It works fine. thank you.
