### ISSUE TITLE
[BUG] Exception: The number columns in the row (5) does not match the values (3)

### ISSUE THREAD

**Issue by Prof1974** [JanoPL/Routeslist#92]
I have installed "RouteList v1.1.2" via Nuget to a web application I am working on and configured it as per the documentation found in the readme file. However, when I run the web application and invoke the URL to the route page, I get the following error: "Exception: The number columns in the row (5) does not match the values (3)" See also the image uploaded below.

![image](https://github.com/JanoPL/Routeslist/assets/40900835/8652a64d-8cde-4d27-9473-2a34eda492c6)

I have configured RouteList in my Program.cs file as follows:

using Serilog;
using Glofind.Infrastructure.Persistence;
using Glofind.Application;
using Glofind;
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using Glofind.Infrastructure.Email;
using Glofind.HtmlEmailLibrary;
using RoutesList.Gen;

IConfiguration configuration = new ConfigurationBuilder()
    .AddJsonFile("appsettings.json")
    .Build();

Log.Logger = new LoggerConfiguration()
.WriteTo.Console()
//.ReadFrom.Configuration(configuration)
.CreateLogger();

try
{
    Log.Information("Application starting up...");

    var builder = WebApplication.CreateBuilder(args);

    builder.Host.UseSerilog((context, loggerConfiguration) =>
    {
        loggerConfiguration.WriteTo.Console();
        loggerConfiguration.ReadFrom.Configuration(context.Configuration);

    });

    //Serilog.Debugging.SelfLog.Enable(Console.WriteLine);

    // Add services to the container.
    builder.Services.AddRazorPages()
        .AddRazorPagesOptions(opts =>
        {
            opts.Conventions.Add(new PageRouteTransformerConvention(new KebabCaseParameterTransformer()));
        });

    builder.Services.AddControllers();

    builder.Services.Configure<RouteOptions>(options =>
    {
        options.LowercaseUrls = true;
        options.LowercaseQueryStrings = true;
        options.AppendTrailingSlash = true;
    });

    builder.Services.AddCors();

    builder.Services.AddHsts(options =>
    {
        options.Preload = true;
        options.IncludeSubDomains = true;
        options.MaxAge = TimeSpan.FromDays(630);
    });

    builder.Services.AddDistributedMemoryCache();

    builder.Services.AddPersistenceServices(builder.Configuration);
    builder.Services.AddApplicationService(builder.Configuration);
    builder.Services.AddEmailServices(builder.Configuration);
    builder.Services.AddRazorTemplateServices();

    //builder.Services.AddSingleton<ResponseTypeManager>();

    builder.Services.AddSession(options =>
    {
        options.IdleTimeout = TimeSpan.FromDays(365);
        options.Cookie.HttpOnly = true;
        options.Cookie.SecurePolicy = CookieSecurePolicy.Always;
        options.Cookie.IsEssential = true;
        options.IdleTimeout = TimeSpan.FromMinutes(60);
    });

    //builder.WebHost.UseStaticWebAssets();

    /* To List all Routes */
    builder.Services.AddRoutesList();

    var app = builder.Build();

    //Register Syncfusion license
    Syncfusion.Licensing.SyncfusionLicenseProvider.RegisterLicense("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");

    // Configure the HTTP request pipeline.
    if (!app.Environment.IsDevelopment())
    {
        //app.UseExceptionHandler("/Error");
        app.UseStatusCodePagesWithReExecute("/Error/{0}");
        // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
        app.UseHsts();
    }

    //app.UseSerilogRequestLogging();

    app.UseHttpsRedirection();
    app.UseStaticFiles();

    app.UseRouting();

    app.UseAuthorization();

    app.UseSession();

    app.MapRazorPages();

	IDictionary<string, string[]> dict = new Dictionary<string, string[]>();

	string[] classes = dict["table"] = new string[2] { "table", "table-striped" };

	app.UseRoutesList(options => {
		options.Tittle = "Title";
		options.Endpoint = "routes";
		options.SetTableClasses(classes);
	});

	app.MapControllers();

    app.Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, "Application start-up failed!");
}
finally
{
    Log.CloseAndFlush();
}

return 0;

**Expected behavior**
To see the routes configured for the application when routing to <domain>/routes

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version latest

**Additional context**
My app is a Razor Pages ASP.NET Core application targeting NET 8.0

**Comment by JanoPL** [comment]
Hi,

Thank you for reporting the bug.

 The issue was related to having two types of routes in your project, MVC controller and Razor pages, which caused that only one could appear in the project. I’ve made a small fix that allows both to be used at the same time.
 
 
I’ve released version 1.1.2.1 which fixes the bug. Download the new version from nuget.org and let me know if it has fixed this error with the incorrect number of columns when adding to the table.

**Comment by Prof1974** [comment]
Hi JanoPL,

Thank you so much!

Problem solved. It works now for me. The quickest bug fix ever and much
appreciated!

Kind regards

Henk

**Comment by Prof1974** [comment]
Awesome, thanks for the update!
